// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4AfHoILQ8Hi_64kEm_W1U1el83pR6Wmg',
    appId: '1:1082587924232:web:19b781095244325f9a8ebd',
    messagingSenderId: '1082587924232',
    projectId: 'ziani-project-e4080',
    authDomain: 'ziani-project-e4080.firebaseapp.com',
    storageBucket: 'ziani-project-e4080.firebasestorage.app',
    measurementId: 'G-ZQX8VBQJT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxRb1yOYsOCQUwnFmXSUVe6qLbSZj4hyM',
    appId: '1:1082587924232:android:ca52662d38f41c449a8ebd',
    messagingSenderId: '1082587924232',
    projectId: 'ziani-project-e4080',
    storageBucket: 'ziani-project-e4080.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcMyZGtRlzp_7yySSfXomPHZKqb7Vp8UY',
    appId: '1:1082587924232:ios:bee3cd1ce1bbc28c9a8ebd',
    messagingSenderId: '1082587924232',
    projectId: 'ziani-project-e4080',
    storageBucket: 'ziani-project-e4080.firebasestorage.app',
    iosBundleId: 'com.example.autoswift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcMyZGtRlzp_7yySSfXomPHZKqb7Vp8UY',
    appId: '1:1082587924232:ios:bee3cd1ce1bbc28c9a8ebd',
    messagingSenderId: '1082587924232',
    projectId: 'ziani-project-e4080',
    storageBucket: 'ziani-project-e4080.firebasestorage.app',
    iosBundleId: 'com.example.autoswift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4AfHoILQ8Hi_64kEm_W1U1el83pR6Wmg',
    appId: '1:1082587924232:web:bb01c75d0eabcde39a8ebd',
    messagingSenderId: '1082587924232',
    projectId: 'ziani-project-e4080',
    authDomain: 'ziani-project-e4080.firebaseapp.com',
    storageBucket: 'ziani-project-e4080.firebasestorage.app',
    measurementId: 'G-PNY7QXLVSH',
  );
}
